fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 4.11.0
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: 2.3.0
  symlinks:
    fish: "#{source_dir}"
